- Cargo.lock
- Cargo.toml
- flake.nix
Update version to 1.0.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.0.0

- .github/workflows/release.yaml
Cross compilation is too hard and GH Actions doesn't have aarch64 runners yet: https://github.com/actions/runner-images/issues/5631
> Disable aarch64-linux builds

- Cargo.lock
- Cargo.toml
- flake.nix
Update version to 1.0.1 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.0.1

- data/env.fish
- data/env.zsh
This fixes extra arguments. Before, you'd see this if you tried to use any arguments with `nix-shell` or `nix develop`:
```
$ nix develop --command whatever
error: unexpected argument '--command' found
note: to pass '--command' as a value, use '-- --command'
Usage: nix-your-shell <SHELL> nix <ARGS>
For more information, try '--help'.
```
> Add `--` to `nix-your-shell` invocations

- Cargo.lock
- Cargo.toml
- flake.nix
Update version to 1.0.2 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.0.2

- .github/labeler.yml
This means PRs that change files in the `data/` directory will be labeled `patch` by default.
> Add `data/` to files that trigger patch-level changes

- README.md
Now that `nix-your-shell` is available in `nixpkgs`, we should have instructions for installing it from `nixpkgs`.
> Add nixpkgs installation instructions to docs

- Cargo.lock
- Cargo.toml
- flake.nix
Update version to 1.1.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.1.0

- src/main.rs
The Nix CLI is inconsistent with the `--command` flag...
We would transform (e.g.) `nix develop -L .#ghc942` into `nix develop --command fish -L .#ghc942`, which Nix interprets as running the command `fish -L .#ghc942` in the shell. This patch puts the `--command fish` bit at the end, instead of at the front, so the `-L .#ghc942` arguments are correctly passed to `nix develop`.
Future work: actually writing some tests lol
> Fix `--command` with `nix develop`

- Cargo.lock
- Cargo.toml
- flake.nix
Update version to 1.1.1 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.1.1

- Cargo.lock
- Cargo.toml
- flake.nix
Update version to 1.2.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.2.0

- Cargo.lock
- Cargo.toml
- flake.nix
Update version to 1.2.1 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.2.1

- Cargo.lock
- Cargo.toml
- flake.nix
Update version to 1.3.0 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.3.0

- .github/workflows/version.yaml
- default.nix
- flake.lock
- flake.nix
- flake.systems.nix
- shell.nix
**Any of these commits may be dropped or rebased should you disapprove.**
I recommend reviewing this PR by individual commit because of the diff-noise produced by the formatter (last commit).
1. Add `meta.mainProgram` (and other `meta` attributes) to the package.
<https://github.com/MercuryTechnologies/nix-your-shell/pull/40/commits/af3c6a8820135c0897e77b7cc6666e99c78a3630>
3. Appease `nil` lint about unused function argument `flake-compat`, replace with `...`.
<https://github.com/MercuryTechnologies/nix-your-shell/pull/40/commits/079602288895d5a1ebb7bbdd670cad1611235a98>
5. Remove usage of `rec` from `packages` output, prefer referencing through `self` for package aliases.
<https://github.com/MercuryTechnologies/nix-your-shell/pull/40/commits/30ebc4953280dcced19fdab8f1ad94a688cfd3bf>
7. …
> Housekeeping

- README.md
- data/env.xsh
- src/main.rs
- src/shell.rs
> Xonsh support

- README.md
- data/env.nu
Comply with changes made in Nushell version `0.87.0`. Rename calling function to not conflict with something user defined. Lastly, rewrite readme section to be more informative.
> Nushell update

- src/main.rs
Logging to stdout breaks sourcing!
> Log to stderr

- src/main.rs
- src/nix.rs
Previously, with `--nom`, `nix-your-shell` would pass all `nix` commands through `nom`, causing unsupported commands (e.g. all but `build`, `develop`, and `shell`) to fail (e.g. it would run `nom flake update`, which errors).
> Fix `nom` support

- Cargo.lock
- Cargo.toml
- data/env.fish.j2
- data/env.nu.j2
- data/env.sh.j2
- data/env.xsh
- data/env.xsh.j2
- src/main.rs
The nu template uses the executable very differently from others, so it ends up trying weird things like `which nix-your-shell --nom`, which fails because `which` doesn't understand `--nom`.
The other shell templates are also broken as shell _scripts_, because they rely on the `nix-your-shell` -> `nix-your-shell $shell` substitution.
Fix everything by using a real template engine.
> Fix nushell with --nom, make shell bits templated

- nix/packages/make-checks.nix
This makes it impossible to mark them required
> Don't include version numbers in check names

- Cargo.toml
- flake.lock
- nix/packages/get-crate-version.nix
- nix/packages/make-release-commit.nix
> Fix release process

- nix/packages/nix-your-shell.nix
Thanks to @spikespaz for spotting this: https://github.com/MercuryTechnologies/nix-your-shell/pull/63#issuecomment-2014855603
> Re-add `generate-config` script

- README.md
`promptInit` is deprecated in stable
> Change `programs.fish.promptInit` to `programs.fish.interactiveShellInit` in README

- Cargo.lock
- Cargo.toml
Update version to 1.4.6 with [cargo-release](https://github.com/crate-ci/cargo-release).
> Release version 1.4.6

- README.md
See #72 for more info.
I confirm that these usage instructions are working correctly.
Aliases are correctly updated:
```python
xonsh.aliases.Aliases(
{
'nix-shell': ExecAlias('/nix/store/cpnv8a4aljqx6jav4x4c6fw7klbhdjsj-nix-your-shell-1.4.6/bin/nix-your-shell  xonsh nix-shell -- @($args)', filename='<exec-alias:nix-shell>'),
'nix': ExecAlias('/nix/store/cpnv8a4aljqx6jav4x4c6fw7klbhdjsj-nix-your-shell-1.4.6/bin/nix-your-shell  xonsh nix -- @($args)', filename='<exec-alias:nix>')})
```
Closes #72
> Update xonsh usage instructions in README.md
